services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    env_file:
      - ./Backend/.env

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
